---
- hosts: all
  become: true

  vars:
    folders:
      - project1
      - project2
      - project3


  tasks:
    - name: Create directories
      file:
        path: "/home/ubuntu/{{ item }}"
        state: directory

      loop: "{{ folders }}"
